### PR TITLE
NO-ISSUE: fixing parameters in openshift template

### PR DESCRIPTION
**Pull request by danmanor**
Parameterize the port, and also hopefully trigger image build now that I have merged the configuration in `app-sre`

### CODE REVIEW

**Comment by osherdp** [comment]
what is the actual fix here?

**Comment by danmanor** [comment]
@osherdp I want to parameterize the port, and also hopefully trigger image build now that I have merged the configuration in app-sre

**Comment by osherdp** [comment]
> @osherdp I want to parameterize the port, and also hopefully trigger image build now that I have merged the configuration in app-sre

ah ok. it's just that the description of this PR says nothing about those two intentions :)

**Comment by danmanor** [comment]
sorry @osherdp

**Comment by rccrdpccl** [comment]
> also hopefully trigger image build

FWIW I think it can be triggered manually without commits

**Pull request merged**
